version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: eventsourcing_database
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
      POSTGRES_DB: django
    ports:
      - "5435:5432"  # Expose on a non-standard port to avoid conflicts
    volumes:
      - .local/postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "django"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
